site_name: My Blog
site_url: https://keygenqt.github.io/articles/

nav:
  - Home:
      - Home: index.md
      - <span class="material-symbols-outlined">description</span> Articles: articles/aurora/index.md
      - <span class="material-symbols-outlined">unknown_document</span> Helps: helps/index.md
      - <span class="material-symbols-outlined">draw</span> Shorts: shorts/index.md
      - <span class="material-symbols-outlined">history_edu</span> Verses: verses/index.md
  - Articles:
      - Aurora OS:
        - Aurora OS: articles/aurora/index.md
        - Hello Emulator!: 'articles/aurora/12_04_2023/index.md'
        - Знакомство с Aurora OS: 'articles/aurora/24_01_2023/index.md'
        - Mission impossible, Aurora + M1: 'articles/aurora/21_05_2023/index.md'
      - Other:
        - Other: articles/other/index.md
        - Философия в ИТ: 'articles/other/18_03_2023/index.md'
        - Amazing Gif: 'articles/other/27_01_2023/index.md'
        - Каррирование в Kotlin: 'articles/other/26_01_2023/index.md'
        - Сложность: 'articles/other/26_01_2021/index.md'
  - Helps:
      - Helps: helps/index.md
      - Toast in Aurora OS: 'helps/_1/index.md'
      - Skeleton in Aurora OS: 'helps/_2/index.md'
      - Splash in Aurora OS: 'helps/_3/index.md'
  - Shorts:
      - Shorts: shorts/index.md
      - Гений: 'shorts/29_03_2022/index.md'
      - Единая вселенная: 'shorts/28_03_2022/index.md'
      - Предел эволюции: 'shorts/27_03_2022/index.md'
      - Голосование: 'shorts/27_03_2022_2/index.md'
      - Бэкап: 'shorts/26_03_2022/index.md'
      - Охота: 'shorts/26_03_2022_2/index.md'
      - Соты: 'shorts/15_03_2022/index.md'
  - Verses:
      - Verses: verses/index.md
      - И вот 10й скоро год: 'verses/22_04_2023/index.md'
      - Аврору я свою построил: 'verses/21_04_2023/index.md'
      - Сословий крах принес свободу: 'verses/30_07_2020/index.md'
      - Ты пробовал работая учиться?: 'verses/29_07_2020/index.md'
      - Высоковольтные лианы: 'verses/28_07_2020/index.md'
      - Наука даст нам жизни вечность: 'verses/27_07_2020/index.md'
      - Где бизнес, нет личному места: 'verses/27_07_2020_2/index.md'
      - Огонь твой вспыхнет и погаснет: 'verses/23_07_2020/index.md'
      - Когда судьба тебе щебечет: 'verses/27_09_2019/index.md'


# Extra
extra_css:
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0
  - docs/assets/main.css
  - /site/assets/main.css
  - /articles/assets/main.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.3.min.js
  - docs/assets/main.js
  - /site/assets/main.js
  - /articles/assets/main.js

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Configuration
theme:
  name: 'material'
  language: 'ru'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.prune
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono